// Generated by delombok at Sun Sep 03 18:47:23 NZST 2017
package ast;

import java.util.Collections;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;
import ast.Ast.Mdf;
import ast.L42F.Cn;
import l42FVisitors.Visitor;
import l42FVisitors.BodyVisitor;

public class L42F {


  public static interface Kind {

    String className(CD cd);

    String boxedClassName(CD cd);
  }

  public static enum SimpleKind implements Kind {
    Class {


      public String className(CD cd) {
        return cd.dbgName();
      }
    },
    Interface {


      public String className(CD cd) {
        return cd.dbgName();
      }
    },
    NativeInt32 {


      public String className(CD cd) {
        return "int";
      }

      public String boxedClassName(CD cd) {
        return "Integer";
      }
    },
    NativeString {


      public String className(CD cd) {
        return "String";
      }
    },
    NativeFloat32 {


      public String className(CD cd) {
        return "float";
      }

      public String boxedClassName(CD cd) {
        return "Float";
      }
    };


    public String boxedClassName(CD cd) {
      return className(cd);
    }
  }

  public static final class CD {
    private final Kind kind;
    private final int cn;
    private final List<String> dbgName;
    private final List<Integer> cns;
    private final List<M> ms;

    public String dbgName() {
      StringBuilder b = new StringBuilder();
      tools.StringBuilders.formatSequence(b, dbgName.iterator(), "£C", s -> b.append(s));
      b.append("£Id" + cn);
      return b.toString();
    }

    public String className() {
      return kind.className(this);
    }

    public String boxedClassName() {
      return kind.boxedClassName(this);
    }

    public String l42ClassName() {
      return dbgName();
    }

    @java.beans.ConstructorProperties({"kind", "cn", "dbgName", "cns", "ms"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD(final Kind kind, final int cn, final List<String> dbgName, final List<Integer> cns, final List<M> ms) {
      this.kind = kind;
      this.cn = cn;
      this.dbgName = dbgName;
      this.cns = cns;
      this.ms = ms;
      assert cn>0;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Kind getKind() {
      return this.kind;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getCn() {
      return this.cn;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<String> getDbgName() {
      return this.dbgName;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<Integer> getCns() {
      return this.cns;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<M> getMs() {
      return this.ms;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.CD)) return false;
      final CD other = (CD)o;
      final java.lang.Object this$kind = this.getKind();
      final java.lang.Object other$kind = other.getKind();
      if (this$kind == null ? other$kind != null : !this$kind.equals(other$kind)) return false;
      if (this.getCn() != other.getCn()) return false;
      final java.lang.Object this$dbgName = this.getDbgName();
      final java.lang.Object other$dbgName = other.getDbgName();
      if (this$dbgName == null ? other$dbgName != null : !this$dbgName.equals(other$dbgName)) return false;
      final java.lang.Object this$cns = this.getCns();
      final java.lang.Object other$cns = other.getCns();
      if (this$cns == null ? other$cns != null : !this$cns.equals(other$cns)) return false;
      final java.lang.Object this$ms = this.getMs();
      final java.lang.Object other$ms = other.getMs();
      if (this$ms == null ? other$ms != null : !this$ms.equals(other$ms)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $kind = this.getKind();
      result = result * PRIME + ($kind == null ? 0 : $kind.hashCode());
      result = result * PRIME + this.getCn();
      final java.lang.Object $dbgName = this.getDbgName();
      result = result * PRIME + ($dbgName == null ? 0 : $dbgName.hashCode());
      final java.lang.Object $cns = this.getCns();
      result = result * PRIME + ($cns == null ? 0 : $cns.hashCode());
      final java.lang.Object $ms = this.getMs();
      result = result * PRIME + ($ms == null ? 0 : $ms.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.CD(kind=" + this.getKind() + ", cn=" + this.getCn() + ", dbgName=" + this.getDbgName() + ", cns=" + this.getCns() + ", ms=" + this.getMs() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD withKind(final Kind kind) {
      return this.kind == kind ? this : new CD(kind, this.cn, this.dbgName, this.cns, this.ms);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD withCn(final int cn) {
      return this.cn == cn ? this : new CD(this.kind, cn, this.dbgName, this.cns, this.ms);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD withDbgName(final List<String> dbgName) {
      return this.dbgName == dbgName ? this : new CD(this.kind, this.cn, dbgName, this.cns, this.ms);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD withCns(final List<Integer> cns) {
      return this.cns == cns ? this : new CD(this.kind, this.cn, this.dbgName, cns, this.ms);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CD withMs(final List<M> ms) {
      return this.ms == ms ? this : new CD(this.kind, this.cn, this.dbgName, this.cns, ms);
    }
  }

  public static final class TX {
    private final T t;
    private final String x;

    @java.beans.ConstructorProperties({"t", "x"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public TX(final T t, final String x) {
      this.t = t;
      this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getT() {
      return this.t;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX() {
      return this.x;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.TX)) return false;
      final TX other = (TX)o;
      final java.lang.Object this$t = this.getT();
      final java.lang.Object other$t = other.getT();
      if (this$t == null ? other$t != null : !this$t.equals(other$t)) return false;
      final java.lang.Object this$x = this.getX();
      final java.lang.Object other$x = other.getX();
      if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $t = this.getT();
      result = result * PRIME + ($t == null ? 0 : $t.hashCode());
      final java.lang.Object $x = this.getX();
      result = result * PRIME + ($x == null ? 0 : $x.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.TX(t=" + this.getT() + ", x=" + this.getX() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public TX withT(final T t) {
      return this.t == t ? this : new TX(t, this.x);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public TX withX(final String x) {
      return this.x == x ? this : new TX(this.t, x);
    }
  }

  public static final class M {
    private final boolean refine;
    private final T returnType;
    private final Ast.MethodSelector selector;
    private final List<TX> txs;
    private final Body body;

    @java.beans.ConstructorProperties({"refine", "returnType", "selector", "txs", "body"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M(final boolean refine, final T returnType, final Ast.MethodSelector selector, final List<TX> txs, final Body body) {
      this.refine = refine;
      this.returnType = returnType;
      this.selector = selector;
      this.txs = txs;
      this.body = body;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean isRefine() {
      return this.refine;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getReturnType() {
      return this.returnType;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.MethodSelector getSelector() {
      return this.selector;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<TX> getTxs() {
      return this.txs;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Body getBody() {
      return this.body;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.M)) return false;
      final M other = (M)o;
      if (this.isRefine() != other.isRefine()) return false;
      final java.lang.Object this$returnType = this.getReturnType();
      final java.lang.Object other$returnType = other.getReturnType();
      if (this$returnType == null ? other$returnType != null : !this$returnType.equals(other$returnType)) return false;
      final java.lang.Object this$selector = this.getSelector();
      final java.lang.Object other$selector = other.getSelector();
      if (this$selector == null ? other$selector != null : !this$selector.equals(other$selector)) return false;
      final java.lang.Object this$txs = this.getTxs();
      final java.lang.Object other$txs = other.getTxs();
      if (this$txs == null ? other$txs != null : !this$txs.equals(other$txs)) return false;
      final java.lang.Object this$body = this.getBody();
      final java.lang.Object other$body = other.getBody();
      if (this$body == null ? other$body != null : !this$body.equals(other$body)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = result * PRIME + (this.isRefine() ? 79 : 97);
      final java.lang.Object $returnType = this.getReturnType();
      result = result * PRIME + ($returnType == null ? 0 : $returnType.hashCode());
      final java.lang.Object $selector = this.getSelector();
      result = result * PRIME + ($selector == null ? 0 : $selector.hashCode());
      final java.lang.Object $txs = this.getTxs();
      result = result * PRIME + ($txs == null ? 0 : $txs.hashCode());
      final java.lang.Object $body = this.getBody();
      result = result * PRIME + ($body == null ? 0 : $body.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.M(refine=" + this.isRefine() + ", returnType=" + this.getReturnType() + ", selector=" + this.getSelector() + ", txs=" + this.getTxs() + ", body=" + this.getBody() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M withRefine(final boolean refine) {
      return this.refine == refine ? this : new M(refine, this.returnType, this.selector, this.txs, this.body);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M withReturnType(final T returnType) {
      return this.returnType == returnType ? this : new M(this.refine, returnType, this.selector, this.txs, this.body);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M withSelector(final Ast.MethodSelector selector) {
      return this.selector == selector ? this : new M(this.refine, this.returnType, selector, this.txs, this.body);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M withTxs(final List<TX> txs) {
      return this.txs == txs ? this : new M(this.refine, this.returnType, this.selector, txs, this.body);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public M withBody(final Body body) {
      return this.body == body ? this : new M(this.refine, this.returnType, this.selector, this.txs, body);
    }
  }

  public static interface Body {

    <T> T accept(BodyVisitor<T> v);
  }

  public static enum SimpleBody implements Body {
    Empty {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitEmpty(this);
      }
    },
    Setter {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitSetter(this);
      }
    },
    Getter {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitGetter(this);
      }
    },
    New {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitNew(this);
      }
    },
    NewWithFwd {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitNewWithFwd(this);
      }
    },
    NewFwd {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitNewFwd(this);
      }
    },
    NativeIntSum {


      public <T> T accept(BodyVisitor<T> v) {
        return v.visitNativeIntSum(this);
      }
    };

  }

  public static interface E extends Body {

    <T> T accept(Visitor<T> v);

    default <T> T accept(BodyVisitor<T> v) {
      return v.visitE(this);
    }
  }

  public static final class Block implements E {
    private final List<D> ds;
    private final List<K> ks;
    private final E e;
    private final T type;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"ds", "ks", "e", "type"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Block(final List<D> ds, final List<K> ks, final E e, final T type) {
      this.ds = ds;
      this.ks = ks;
      this.e = e;
      this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<D> getDs() {
      return this.ds;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<K> getKs() {
      return this.ks;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getE() {
      return this.e;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getType() {
      return this.type;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Block)) return false;
      final Block other = (Block)o;
      final java.lang.Object this$ds = this.getDs();
      final java.lang.Object other$ds = other.getDs();
      if (this$ds == null ? other$ds != null : !this$ds.equals(other$ds)) return false;
      final java.lang.Object this$ks = this.getKs();
      final java.lang.Object other$ks = other.getKs();
      if (this$ks == null ? other$ks != null : !this$ks.equals(other$ks)) return false;
      final java.lang.Object this$e = this.getE();
      final java.lang.Object other$e = other.getE();
      if (this$e == null ? other$e != null : !this$e.equals(other$e)) return false;
      final java.lang.Object this$type = this.getType();
      final java.lang.Object other$type = other.getType();
      if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $ds = this.getDs();
      result = result * PRIME + ($ds == null ? 0 : $ds.hashCode());
      final java.lang.Object $ks = this.getKs();
      result = result * PRIME + ($ks == null ? 0 : $ks.hashCode());
      final java.lang.Object $e = this.getE();
      result = result * PRIME + ($e == null ? 0 : $e.hashCode());
      final java.lang.Object $type = this.getType();
      result = result * PRIME + ($type == null ? 0 : $type.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Block(ds=" + this.getDs() + ", ks=" + this.getKs() + ", e=" + this.getE() + ", type=" + this.getType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Block withDs(final List<D> ds) {
      return this.ds == ds ? this : new Block(ds, this.ks, this.e, this.type);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Block withKs(final List<K> ks) {
      return this.ks == ks ? this : new Block(this.ds, ks, this.e, this.type);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Block withE(final E e) {
      return this.e == e ? this : new Block(this.ds, this.ks, e, this.type);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Block withType(final T type) {
      return this.type == type ? this : new Block(this.ds, this.ks, this.e, type);
    }
  }

  public static final class X implements E {
    private final String inner;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"inner"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public X(final String inner) {
      this.inner = inner;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getInner() {
      return this.inner;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.X)) return false;
      final X other = (X)o;
      final java.lang.Object this$inner = this.getInner();
      final java.lang.Object other$inner = other.getInner();
      if (this$inner == null ? other$inner != null : !this$inner.equals(other$inner)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $inner = this.getInner();
      result = result * PRIME + ($inner == null ? 0 : $inner.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.X(inner=" + this.getInner() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public X withInner(final String inner) {
      return this.inner == inner ? this : new X(inner);
    }
  }

  public static final class Cn implements E {
    private final int inner;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }
    public static final Cn cnAny = new Cn(1);
    public static final Cn cnVoid = new Cn(2);
    public static final Cn cnLibrary = new Cn(3);
    public static final Cn cnResource = new Cn(4);
    public static final Cn cnFwd = new Cn(5);//no here is generated file

    @java.beans.ConstructorProperties({"inner"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Cn(final int inner) {
      this.inner = inner;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getInner() {
      return this.inner;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Cn)) return false;
      final Cn other = (Cn)o;
      if (this.getInner() != other.getInner()) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = result * PRIME + this.getInner();
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Cn(inner=" + this.getInner() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Cn withInner(final int inner) {
      return this.inner == inner ? this : new Cn(inner);
    }
  }

  public static final class _void implements E {

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public _void() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F._void)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      int result = 1;
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F._void()";
    }
  }

  public static final class Null implements E {

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Null() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Null)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      int result = 1;
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Null()";
    }
  }

  public static final class Unreachable implements E {

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Unreachable() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Unreachable)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      int result = 1;
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Unreachable()";
    }
  }

  public static final class BreakLoop implements E {

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public BreakLoop() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.BreakLoop)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      int result = 1;
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.BreakLoop()";
    }
  }

  public static final class Throw implements E {
    private final Ast.SignalKind kind;
    private final String x;
    private final T tContext;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"kind", "x", "tContext"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Throw(final Ast.SignalKind kind, final String x, final T tContext) {
      this.kind = kind;
      this.x = x;
      this.tContext = tContext;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.SignalKind getKind() {
      return this.kind;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX() {
      return this.x;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getTContext() {
      return this.tContext;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Throw)) return false;
      final Throw other = (Throw)o;
      final java.lang.Object this$kind = this.getKind();
      final java.lang.Object other$kind = other.getKind();
      if (this$kind == null ? other$kind != null : !this$kind.equals(other$kind)) return false;
      final java.lang.Object this$x = this.getX();
      final java.lang.Object other$x = other.getX();
      if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
      final java.lang.Object this$tContext = this.getTContext();
      final java.lang.Object other$tContext = other.getTContext();
      if (this$tContext == null ? other$tContext != null : !this$tContext.equals(other$tContext)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $kind = this.getKind();
      result = result * PRIME + ($kind == null ? 0 : $kind.hashCode());
      final java.lang.Object $x = this.getX();
      result = result * PRIME + ($x == null ? 0 : $x.hashCode());
      final java.lang.Object $tContext = this.getTContext();
      result = result * PRIME + ($tContext == null ? 0 : $tContext.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Throw(kind=" + this.getKind() + ", x=" + this.getX() + ", tContext=" + this.getTContext() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Throw withKind(final Ast.SignalKind kind) {
      return this.kind == kind ? this : new Throw(kind, this.x, this.tContext);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Throw withX(final String x) {
      return this.x == x ? this : new Throw(this.kind, x, this.tContext);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Throw withTContext(final T tContext) {
      return this.tContext == tContext ? this : new Throw(this.kind, this.x, tContext);
    }
  }

  public static final class Loop implements E {
    private final E inner;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"inner"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Loop(final E inner) {
      this.inner = inner;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getInner() {
      return this.inner;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Loop)) return false;
      final Loop other = (Loop)o;
      final java.lang.Object this$inner = this.getInner();
      final java.lang.Object other$inner = other.getInner();
      if (this$inner == null ? other$inner != null : !this$inner.equals(other$inner)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $inner = this.getInner();
      result = result * PRIME + ($inner == null ? 0 : $inner.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Loop(inner=" + this.getInner() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Loop withInner(final E inner) {
      return this.inner == inner ? this : new Loop(inner);
    }
  }

  public static final class Call implements E {
    private final int cn;
    private final Ast.MethodSelector ms;
    private final List<String> xs;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"cn", "ms", "xs"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Call(final int cn, final Ast.MethodSelector ms, final List<String> xs) {
      this.cn = cn;
      this.ms = ms;
      this.xs = xs;
      assert cn>0;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getCn() {
      return this.cn;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.MethodSelector getMs() {
      return this.ms;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<String> getXs() {
      return this.xs;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Call)) return false;
      final Call other = (Call)o;
      if (this.getCn() != other.getCn()) return false;
      final java.lang.Object this$ms = this.getMs();
      final java.lang.Object other$ms = other.getMs();
      if (this$ms == null ? other$ms != null : !this$ms.equals(other$ms)) return false;
      final java.lang.Object this$xs = this.getXs();
      final java.lang.Object other$xs = other.getXs();
      if (this$xs == null ? other$xs != null : !this$xs.equals(other$xs)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = result * PRIME + this.getCn();
      final java.lang.Object $ms = this.getMs();
      result = result * PRIME + ($ms == null ? 0 : $ms.hashCode());
      final java.lang.Object $xs = this.getXs();
      result = result * PRIME + ($xs == null ? 0 : $xs.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Call(cn=" + this.getCn() + ", ms=" + this.getMs() + ", xs=" + this.getXs() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Call withCn(final int cn) {
      return this.cn == cn ? this : new Call(cn, this.ms, this.xs);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Call withMs(final Ast.MethodSelector ms) {
      return this.ms == ms ? this : new Call(this.cn, ms, this.xs);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Call withXs(final List<String> xs) {
      return this.xs == xs ? this : new Call(this.cn, this.ms, xs);
    }
  }

  public static final class Use implements E {
    private final Ast.Doc doc;
    private final platformSpecific.fakeInternet.PluginWithPart.UsingInfo ui;
    private final Ast.MethodSelector ms;
    private final List<String> xs;
    private final E inner;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"doc", "ui", "ms", "xs", "inner"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use(final Ast.Doc doc, final platformSpecific.fakeInternet.PluginWithPart.UsingInfo ui, final Ast.MethodSelector ms, final List<String> xs, final E inner) {
      this.doc = doc;
      this.ui = ui;
      this.ms = ms;
      this.xs = xs;
      this.inner = inner;
      assert ui!=null;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.Doc getDoc() {
      return this.doc;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public platformSpecific.fakeInternet.PluginWithPart.UsingInfo getUi() {
      return this.ui;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.MethodSelector getMs() {
      return this.ms;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public List<String> getXs() {
      return this.xs;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getInner() {
      return this.inner;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Use)) return false;
      final Use other = (Use)o;
      final java.lang.Object this$doc = this.getDoc();
      final java.lang.Object other$doc = other.getDoc();
      if (this$doc == null ? other$doc != null : !this$doc.equals(other$doc)) return false;
      final java.lang.Object this$ui = this.getUi();
      final java.lang.Object other$ui = other.getUi();
      if (this$ui == null ? other$ui != null : !this$ui.equals(other$ui)) return false;
      final java.lang.Object this$ms = this.getMs();
      final java.lang.Object other$ms = other.getMs();
      if (this$ms == null ? other$ms != null : !this$ms.equals(other$ms)) return false;
      final java.lang.Object this$xs = this.getXs();
      final java.lang.Object other$xs = other.getXs();
      if (this$xs == null ? other$xs != null : !this$xs.equals(other$xs)) return false;
      final java.lang.Object this$inner = this.getInner();
      final java.lang.Object other$inner = other.getInner();
      if (this$inner == null ? other$inner != null : !this$inner.equals(other$inner)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $doc = this.getDoc();
      result = result * PRIME + ($doc == null ? 0 : $doc.hashCode());
      final java.lang.Object $ui = this.getUi();
      result = result * PRIME + ($ui == null ? 0 : $ui.hashCode());
      final java.lang.Object $ms = this.getMs();
      result = result * PRIME + ($ms == null ? 0 : $ms.hashCode());
      final java.lang.Object $xs = this.getXs();
      result = result * PRIME + ($xs == null ? 0 : $xs.hashCode());
      final java.lang.Object $inner = this.getInner();
      result = result * PRIME + ($inner == null ? 0 : $inner.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Use(doc=" + this.getDoc() + ", ui=" + this.getUi() + ", ms=" + this.getMs() + ", xs=" + this.getXs() + ", inner=" + this.getInner() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use withDoc(final Ast.Doc doc) {
      return this.doc == doc ? this : new Use(doc, this.ui, this.ms, this.xs, this.inner);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use withUi(final platformSpecific.fakeInternet.PluginWithPart.UsingInfo ui) {
      return this.ui == ui ? this : new Use(this.doc, ui, this.ms, this.xs, this.inner);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use withMs(final Ast.MethodSelector ms) {
      return this.ms == ms ? this : new Use(this.doc, this.ui, ms, this.xs, this.inner);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use withXs(final List<String> xs) {
      return this.xs == xs ? this : new Use(this.doc, this.ui, this.ms, xs, this.inner);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Use withInner(final E inner) {
      return this.inner == inner ? this : new Use(this.doc, this.ui, this.ms, this.xs, inner);
    }
  }

  public static final class If implements E {
    private final String condition;
    private final E then;
    private final E _else;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"condition", "then", "_else"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public If(final String condition, final E then, final E _else) {
      this.condition = condition;
      this.then = then;
      this._else = _else;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getCondition() {
      return this.condition;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getThen() {
      return this.then;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E get_else() {
      return this._else;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.If)) return false;
      final If other = (If)o;
      final java.lang.Object this$condition = this.getCondition();
      final java.lang.Object other$condition = other.getCondition();
      if (this$condition == null ? other$condition != null : !this$condition.equals(other$condition)) return false;
      final java.lang.Object this$then = this.getThen();
      final java.lang.Object other$then = other.getThen();
      if (this$then == null ? other$then != null : !this$then.equals(other$then)) return false;
      final java.lang.Object this$_else = this.get_else();
      final java.lang.Object other$_else = other.get_else();
      if (this$_else == null ? other$_else != null : !this$_else.equals(other$_else)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $condition = this.getCondition();
      result = result * PRIME + ($condition == null ? 0 : $condition.hashCode());
      final java.lang.Object $then = this.getThen();
      result = result * PRIME + ($then == null ? 0 : $then.hashCode());
      final java.lang.Object $_else = this.get_else();
      result = result * PRIME + ($_else == null ? 0 : $_else.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.If(condition=" + this.getCondition() + ", then=" + this.getThen() + ", _else=" + this.get_else() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public If withCondition(final String condition) {
      return this.condition == condition ? this : new If(condition, this.then, this._else);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public If withThen(final E then) {
      return this.then == then ? this : new If(this.condition, then, this._else);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public If with_else(final E _else) {
      return this._else == _else ? this : new If(this.condition, this.then, _else);
    }
  }

  public static final class Update implements E {
    private final String x1;
    private final String x2;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"x1", "x2"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Update(final String x1, final String x2) {
      this.x1 = x1;
      this.x2 = x2;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX1() {
      return this.x1;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX2() {
      return this.x2;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Update)) return false;
      final Update other = (Update)o;
      final java.lang.Object this$x1 = this.getX1();
      final java.lang.Object other$x1 = other.getX1();
      if (this$x1 == null ? other$x1 != null : !this$x1.equals(other$x1)) return false;
      final java.lang.Object this$x2 = this.getX2();
      final java.lang.Object other$x2 = other.getX2();
      if (this$x2 == null ? other$x2 != null : !this$x2.equals(other$x2)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $x1 = this.getX1();
      result = result * PRIME + ($x1 == null ? 0 : $x1.hashCode());
      final java.lang.Object $x2 = this.getX2();
      result = result * PRIME + ($x2 == null ? 0 : $x2.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Update(x1=" + this.getX1() + ", x2=" + this.getX2() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Update withX1(final String x1) {
      return this.x1 == x1 ? this : new Update(x1, this.x2);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Update withX2(final String x2) {
      return this.x2 == x2 ? this : new Update(this.x1, x2);
    }
  }

  public static final class Cast implements E {
    private final T t;
    private final String x;

    @Override
    public <T> T accept(Visitor<T> v) {
      return v.visit(this);
    }

    @java.beans.ConstructorProperties({"t", "x"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Cast(final T t, final String x) {
      this.t = t;
      this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getT() {
      return this.t;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX() {
      return this.x;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.Cast)) return false;
      final Cast other = (Cast)o;
      final java.lang.Object this$t = this.getT();
      final java.lang.Object other$t = other.getT();
      if (this$t == null ? other$t != null : !this$t.equals(other$t)) return false;
      final java.lang.Object this$x = this.getX();
      final java.lang.Object other$x = other.getX();
      if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $t = this.getT();
      result = result * PRIME + ($t == null ? 0 : $t.hashCode());
      final java.lang.Object $x = this.getX();
      result = result * PRIME + ($x == null ? 0 : $x.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.Cast(t=" + this.getT() + ", x=" + this.getX() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Cast withT(final T t) {
      return this.t == t ? this : new Cast(t, this.x);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Cast withX(final String x) {
      return this.x == x ? this : new Cast(this.t, x);
    }
  }

  public static final class K {
    private final Ast.SignalKind kind;
    private final T t;
    private final String x;
    private final E e;

    @java.beans.ConstructorProperties({"kind", "t", "x", "e"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public K(final Ast.SignalKind kind, final T t, final String x, final E e) {
      this.kind = kind;
      this.t = t;
      this.x = x;
      this.e = e;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.SignalKind getKind() {
      return this.kind;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getT() {
      return this.t;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX() {
      return this.x;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getE() {
      return this.e;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.K)) return false;
      final K other = (K)o;
      final java.lang.Object this$kind = this.getKind();
      final java.lang.Object other$kind = other.getKind();
      if (this$kind == null ? other$kind != null : !this$kind.equals(other$kind)) return false;
      final java.lang.Object this$t = this.getT();
      final java.lang.Object other$t = other.getT();
      if (this$t == null ? other$t != null : !this$t.equals(other$t)) return false;
      final java.lang.Object this$x = this.getX();
      final java.lang.Object other$x = other.getX();
      if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
      final java.lang.Object this$e = this.getE();
      final java.lang.Object other$e = other.getE();
      if (this$e == null ? other$e != null : !this$e.equals(other$e)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $kind = this.getKind();
      result = result * PRIME + ($kind == null ? 0 : $kind.hashCode());
      final java.lang.Object $t = this.getT();
      result = result * PRIME + ($t == null ? 0 : $t.hashCode());
      final java.lang.Object $x = this.getX();
      result = result * PRIME + ($x == null ? 0 : $x.hashCode());
      final java.lang.Object $e = this.getE();
      result = result * PRIME + ($e == null ? 0 : $e.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.K(kind=" + this.getKind() + ", t=" + this.getT() + ", x=" + this.getX() + ", e=" + this.getE() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public K withKind(final Ast.SignalKind kind) {
      return this.kind == kind ? this : new K(kind, this.t, this.x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public K withT(final T t) {
      return this.t == t ? this : new K(this.kind, t, this.x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public K withX(final String x) {
      return this.x == x ? this : new K(this.kind, this.t, x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public K withE(final E e) {
      return this.e == e ? this : new K(this.kind, this.t, this.x, e);
    }
  }

  public static final class D {
    private final boolean var;
    private final T t;
    private final String x;
    private final E e;

    @java.beans.ConstructorProperties({"var", "t", "x", "e"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public D(final boolean var, final T t, final String x, final E e) {
      this.var = var;
      this.t = t;
      this.x = x;
      this.e = e;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean isVar() {
      return this.var;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T getT() {
      return this.t;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getX() {
      return this.x;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public E getE() {
      return this.e;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.D)) return false;
      final D other = (D)o;
      if (this.isVar() != other.isVar()) return false;
      final java.lang.Object this$t = this.getT();
      final java.lang.Object other$t = other.getT();
      if (this$t == null ? other$t != null : !this$t.equals(other$t)) return false;
      final java.lang.Object this$x = this.getX();
      final java.lang.Object other$x = other.getX();
      if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
      final java.lang.Object this$e = this.getE();
      final java.lang.Object other$e = other.getE();
      if (this$e == null ? other$e != null : !this$e.equals(other$e)) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = result * PRIME + (this.isVar() ? 79 : 97);
      final java.lang.Object $t = this.getT();
      result = result * PRIME + ($t == null ? 0 : $t.hashCode());
      final java.lang.Object $x = this.getX();
      result = result * PRIME + ($x == null ? 0 : $x.hashCode());
      final java.lang.Object $e = this.getE();
      result = result * PRIME + ($e == null ? 0 : $e.hashCode());
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.D(var=" + this.isVar() + ", t=" + this.getT() + ", x=" + this.getX() + ", e=" + this.getE() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public D withVar(final boolean var) {
      return this.var == var ? this : new D(var, this.t, this.x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public D withT(final T t) {
      return this.t == t ? this : new D(this.var, t, this.x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public D withX(final String x) {
      return this.x == x ? this : new D(this.var, this.t, x, this.e);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public D withE(final E e) {
      return this.e == e ? this : new D(this.var, this.t, this.x, e);
    }
  }

  public static final class T {
    private final Ast.Mdf mdf;
    private final int cn;
    public static final T immAny = new T(Mdf.Immutable, Cn.cnAny.inner);
    public static final T immVoid = new T(Mdf.Immutable, Cn.cnVoid.inner);
    public static final T immLibrary = new T(Mdf.Immutable, Cn.cnLibrary.inner);
    public static final T classAny = new T(Mdf.Class, Cn.cnAny.inner);

    @java.beans.ConstructorProperties({"mdf", "cn"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T(final Ast.Mdf mdf, final int cn) {
      this.mdf = mdf;
      this.cn = cn;
      assert cn>0;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Ast.Mdf getMdf() {
      return this.mdf;
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int getCn() {
      return this.cn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof L42F.T)) return false;
      final T other = (T)o;
      final java.lang.Object this$mdf = this.getMdf();
      final java.lang.Object other$mdf = other.getMdf();
      if (this$mdf == null ? other$mdf != null : !this$mdf.equals(other$mdf)) return false;
      if (this.getCn() != other.getCn()) return false;
      return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $mdf = this.getMdf();
      result = result * PRIME + ($mdf == null ? 0 : $mdf.hashCode());
      result = result * PRIME + this.getCn();
      return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "L42F.T(mdf=" + this.getMdf() + ", cn=" + this.getCn() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T withMdf(final Ast.Mdf mdf) {
      return this.mdf == mdf ? this : new T(mdf, this.cn);
    }

    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public T withCn(final int cn) {
      return this.cn == cn ? this : new T(this.mdf, cn);
    }
  }
}