// Generated by delombok at Thu Aug 20 11:39:19 CEST 2015
package ast;

import lombok.NonNull;
import ast.Ast.MethodSelector;
import ast.Ast.Path;
import ast.ExpCore.*;

public class Util {
  
  
  public static final class CsMx {
    @NonNull
    private final java.util.List<String> cs;
    @NonNull
    private final MethodSelector ms;
    
    public String toString() {
      String prefix = "Outer0";
      if (!cs.isEmpty()) {
        prefix = String.join("::", cs);
      }
      return prefix + "." + ms;
    }
    
    @java.beans.ConstructorProperties({"cs", "ms"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CsMx(@NonNull final java.util.List<String> cs, @NonNull final MethodSelector ms) {
      if (cs == null) {
        throw new java.lang.NullPointerException("cs");
      }
      if (ms == null) {
        throw new java.lang.NullPointerException("ms");
      }
      this.cs = cs;
      this.ms = ms;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.util.List<String> getCs() {
      return this.cs;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodSelector getMs() {
      return this.ms;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.CsMx)) return false;
      final CsMx other = (CsMx)o;
      final java.lang.Object this$cs = this.getCs();
      final java.lang.Object other$cs = other.getCs();
      if (this$cs == null ? other$cs != null : !this$cs.equals(other$cs)) return false;
      final java.lang.Object this$ms = this.getMs();
      final java.lang.Object other$ms = other.getMs();
      if (this$ms == null ? other$ms != null : !this$ms.equals(other$ms)) return false;
      return true;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $cs = this.getCs();
      result = result * PRIME + ($cs == null ? 0 : $cs.hashCode());
      final java.lang.Object $ms = this.getMs();
      result = result * PRIME + ($ms == null ? 0 : $ms.hashCode());
      return result;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CsMx withCs(@NonNull final java.util.List<String> cs) {
      if (cs == null) {
        throw new java.lang.NullPointerException("cs");
      }
      return this.cs == cs ? this : new CsMx(cs, this.ms);
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public CsMx withMs(@NonNull final MethodSelector ms) {
      if (ms == null) {
        throw new java.lang.NullPointerException("ms");
      }
      return this.ms == ms ? this : new CsMx(this.cs, ms);
    }
  }
  
  public static final class PathMx {
    @NonNull
    private final Path path;
    @NonNull
    private final MethodSelector ms;
    
    public String toString() {
      return "" + path + "." + ms;
    }
    
    @java.beans.ConstructorProperties({"path", "ms"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMx(@NonNull final Path path, @NonNull final MethodSelector ms) {
      if (path == null) {
        throw new java.lang.NullPointerException("path");
      }
      if (ms == null) {
        throw new java.lang.NullPointerException("ms");
      }
      this.path = path;
      this.ms = ms;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Path getPath() {
      return this.path;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodSelector getMs() {
      return this.ms;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.PathMx)) return false;
      final PathMx other = (PathMx)o;
      final java.lang.Object this$path = this.getPath();
      final java.lang.Object other$path = other.getPath();
      if (this$path == null ? other$path != null : !this$path.equals(other$path)) return false;
      final java.lang.Object this$ms = this.getMs();
      final java.lang.Object other$ms = other.getMs();
      if (this$ms == null ? other$ms != null : !this$ms.equals(other$ms)) return false;
      return true;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $path = this.getPath();
      result = result * PRIME + ($path == null ? 0 : $path.hashCode());
      final java.lang.Object $ms = this.getMs();
      result = result * PRIME + ($ms == null ? 0 : $ms.hashCode());
      return result;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMx withPath(@NonNull final Path path) {
      if (path == null) {
        throw new java.lang.NullPointerException("path");
      }
      return this.path == path ? this : new PathMx(path, this.ms);
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMx withMs(@NonNull final MethodSelector ms) {
      if (ms == null) {
        throw new java.lang.NullPointerException("ms");
      }
      return this.ms == ms ? this : new PathMx(this.path, ms);
    }
  }
  
  public static final class PathMxMx {
    @NonNull
    private final Path path;
    @NonNull
    private final MethodSelector ms1;
    @NonNull
    private final MethodSelector ms2;
    
    @java.beans.ConstructorProperties({"path", "ms1", "ms2"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMxMx(@NonNull final Path path, @NonNull final MethodSelector ms1, @NonNull final MethodSelector ms2) {
      if (path == null) {
        throw new java.lang.NullPointerException("path");
      }
      if (ms1 == null) {
        throw new java.lang.NullPointerException("ms1");
      }
      if (ms2 == null) {
        throw new java.lang.NullPointerException("ms2");
      }
      this.path = path;
      this.ms1 = ms1;
      this.ms2 = ms2;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Path getPath() {
      return this.path;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodSelector getMs1() {
      return this.ms1;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodSelector getMs2() {
      return this.ms2;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.PathMxMx)) return false;
      final PathMxMx other = (PathMxMx)o;
      final java.lang.Object this$path = this.getPath();
      final java.lang.Object other$path = other.getPath();
      if (this$path == null ? other$path != null : !this$path.equals(other$path)) return false;
      final java.lang.Object this$ms1 = this.getMs1();
      final java.lang.Object other$ms1 = other.getMs1();
      if (this$ms1 == null ? other$ms1 != null : !this$ms1.equals(other$ms1)) return false;
      final java.lang.Object this$ms2 = this.getMs2();
      final java.lang.Object other$ms2 = other.getMs2();
      if (this$ms2 == null ? other$ms2 != null : !this$ms2.equals(other$ms2)) return false;
      return true;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $path = this.getPath();
      result = result * PRIME + ($path == null ? 0 : $path.hashCode());
      final java.lang.Object $ms1 = this.getMs1();
      result = result * PRIME + ($ms1 == null ? 0 : $ms1.hashCode());
      final java.lang.Object $ms2 = this.getMs2();
      result = result * PRIME + ($ms2 == null ? 0 : $ms2.hashCode());
      return result;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.lang.String toString() {
      return "Util.PathMxMx(path=" + this.getPath() + ", ms1=" + this.getMs1() + ", ms2=" + this.getMs2() + ")";
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMxMx withPath(@NonNull final Path path) {
      if (path == null) {
        throw new java.lang.NullPointerException("path");
      }
      return this.path == path ? this : new PathMxMx(path, this.ms1, this.ms2);
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMxMx withMs1(@NonNull final MethodSelector ms1) {
      if (ms1 == null) {
        throw new java.lang.NullPointerException("ms1");
      }
      return this.ms1 == ms1 ? this : new PathMxMx(this.path, ms1, this.ms2);
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathMxMx withMs2(@NonNull final MethodSelector ms2) {
      if (ms2 == null) {
        throw new java.lang.NullPointerException("ms2");
      }
      return this.ms2 == ms2 ? this : new PathMxMx(this.path, this.ms1, ms2);
    }
  }
  
  public static final class PathPath {
    @NonNull
    private final Path path1;
    @NonNull
    private final Path path2;
    
    public String toString() {
      return "" + path1 + "->" + path2;
    }
    
    @java.beans.ConstructorProperties({"path1", "path2"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathPath(@NonNull final Path path1, @NonNull final Path path2) {
      if (path1 == null) {
        throw new java.lang.NullPointerException("path1");
      }
      if (path2 == null) {
        throw new java.lang.NullPointerException("path2");
      }
      this.path1 = path1;
      this.path2 = path2;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Path getPath1() {
      return this.path1;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Path getPath2() {
      return this.path2;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.PathPath)) return false;
      final PathPath other = (PathPath)o;
      final java.lang.Object this$path1 = this.getPath1();
      final java.lang.Object other$path1 = other.getPath1();
      if (this$path1 == null ? other$path1 != null : !this$path1.equals(other$path1)) return false;
      final java.lang.Object this$path2 = this.getPath2();
      final java.lang.Object other$path2 = other.getPath2();
      if (this$path2 == null ? other$path2 != null : !this$path2.equals(other$path2)) return false;
      return true;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $path1 = this.getPath1();
      result = result * PRIME + ($path1 == null ? 0 : $path1.hashCode());
      final java.lang.Object $path2 = this.getPath2();
      result = result * PRIME + ($path2 == null ? 0 : $path2.hashCode());
      return result;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathPath withPath1(@NonNull final Path path1) {
      if (path1 == null) {
        throw new java.lang.NullPointerException("path1");
      }
      return this.path1 == path1 ? this : new PathPath(path1, this.path2);
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public PathPath withPath2(@NonNull final Path path2) {
      if (path2 == null) {
        throw new java.lang.NullPointerException("path2");
      }
      return this.path2 == path2 ? this : new PathPath(this.path1, path2);
    }
  }
  
  public static class MethodLocator {
    @NonNull
    java.util.List<ClassB.Member> mTail;
    @NonNull
    java.util.List<Integer> mPos;
    ClassB.MethodWithType that;
    MethodSelector newName;
    
    public String toString() {
      return coreVisitors.PathAnnotateClass.computeComment(mTail, mPos) + that.getMs() + newName;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.util.List<ClassB.Member> getMTail() {
      return this.mTail;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.util.List<Integer> getMPos() {
      return this.mPos;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public ClassB.MethodWithType getThat() {
      return this.that;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodSelector getNewName() {
      return this.newName;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setMTail(@NonNull final java.util.List<ClassB.Member> mTail) {
      if (mTail == null) {
        throw new java.lang.NullPointerException("mTail");
      }
      this.mTail = mTail;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setMPos(@NonNull final java.util.List<Integer> mPos) {
      if (mPos == null) {
        throw new java.lang.NullPointerException("mPos");
      }
      this.mPos = mPos;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setThat(final ClassB.MethodWithType that) {
      this.that = that;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setNewName(final MethodSelector newName) {
      this.newName = newName;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.MethodLocator)) return false;
      final MethodLocator other = (MethodLocator)o;
      if (!other.canEqual((java.lang.Object)this)) return false;
      final java.lang.Object this$mTail = this.getMTail();
      final java.lang.Object other$mTail = other.getMTail();
      if (this$mTail == null ? other$mTail != null : !this$mTail.equals(other$mTail)) return false;
      final java.lang.Object this$mPos = this.getMPos();
      final java.lang.Object other$mPos = other.getMPos();
      if (this$mPos == null ? other$mPos != null : !this$mPos.equals(other$mPos)) return false;
      final java.lang.Object this$that = this.getThat();
      final java.lang.Object other$that = other.getThat();
      if (this$that == null ? other$that != null : !this$that.equals(other$that)) return false;
      final java.lang.Object this$newName = this.getNewName();
      final java.lang.Object other$newName = other.getNewName();
      if (this$newName == null ? other$newName != null : !this$newName.equals(other$newName)) return false;
      return true;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
      return other instanceof Util.MethodLocator;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $mTail = this.getMTail();
      result = result * PRIME + ($mTail == null ? 0 : $mTail.hashCode());
      final java.lang.Object $mPos = this.getMPos();
      result = result * PRIME + ($mPos == null ? 0 : $mPos.hashCode());
      final java.lang.Object $that = this.getThat();
      result = result * PRIME + ($that == null ? 0 : $that.hashCode());
      final java.lang.Object $newName = this.getNewName();
      result = result * PRIME + ($newName == null ? 0 : $newName.hashCode());
      return result;
    }
    
    @java.beans.ConstructorProperties({"mTail", "mPos", "that", "newName"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public MethodLocator(@NonNull final java.util.List<ClassB.Member> mTail, @NonNull final java.util.List<Integer> mPos, final ClassB.MethodWithType that, final MethodSelector newName) {
      if (mTail == null) {
        throw new java.lang.NullPointerException("mTail");
      }
      if (mPos == null) {
        throw new java.lang.NullPointerException("mPos");
      }
      this.mTail = mTail;
      this.mPos = mPos;
      this.that = that;
      this.newName = newName;
    }
  }
  
  public static class NestedLocator {
    @NonNull
    java.util.List<ClassB.Member> mTail;
    @NonNull
    java.util.List<Integer> mPos;
    @NonNull
    String that;
    String newName;
    Path newPath;//either newName or newPath always null
    
    public String toString() {
      return coreVisitors.PathAnnotateClass.computeComment(mTail, mPos) + that + newName;
    }
    
    @java.beans.ConstructorProperties({"mTail", "mPos", "that"})
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public NestedLocator(@NonNull final java.util.List<ClassB.Member> mTail, @NonNull final java.util.List<Integer> mPos, @NonNull final String that) {
      if (mTail == null) {
        throw new java.lang.NullPointerException("mTail");
      }
      if (mPos == null) {
        throw new java.lang.NullPointerException("mPos");
      }
      if (that == null) {
        throw new java.lang.NullPointerException("that");
      }
      this.mTail = mTail;
      this.mPos = mPos;
      this.that = that;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.util.List<ClassB.Member> getMTail() {
      return this.mTail;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public java.util.List<Integer> getMPos() {
      return this.mPos;
    }
    
    @NonNull
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getThat() {
      return this.that;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public String getNewName() {
      return this.newName;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public Path getNewPath() {
      return this.newPath;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setMTail(@NonNull final java.util.List<ClassB.Member> mTail) {
      if (mTail == null) {
        throw new java.lang.NullPointerException("mTail");
      }
      this.mTail = mTail;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setMPos(@NonNull final java.util.List<Integer> mPos) {
      if (mPos == null) {
        throw new java.lang.NullPointerException("mPos");
      }
      this.mPos = mPos;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setThat(@NonNull final String that) {
      if (that == null) {
        throw new java.lang.NullPointerException("that");
      }
      this.that = that;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setNewName(final String newName) {
      this.newName = newName;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public void setNewPath(final Path newPath) {
      this.newPath = newPath;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public boolean equals(final java.lang.Object o) {
      if (o == this) return true;
      if (!(o instanceof Util.NestedLocator)) return false;
      final NestedLocator other = (NestedLocator)o;
      if (!other.canEqual((java.lang.Object)this)) return false;
      final java.lang.Object this$mTail = this.getMTail();
      final java.lang.Object other$mTail = other.getMTail();
      if (this$mTail == null ? other$mTail != null : !this$mTail.equals(other$mTail)) return false;
      final java.lang.Object this$mPos = this.getMPos();
      final java.lang.Object other$mPos = other.getMPos();
      if (this$mPos == null ? other$mPos != null : !this$mPos.equals(other$mPos)) return false;
      final java.lang.Object this$that = this.getThat();
      final java.lang.Object other$that = other.getThat();
      if (this$that == null ? other$that != null : !this$that.equals(other$that)) return false;
      final java.lang.Object this$newName = this.getNewName();
      final java.lang.Object other$newName = other.getNewName();
      if (this$newName == null ? other$newName != null : !this$newName.equals(other$newName)) return false;
      final java.lang.Object this$newPath = this.getNewPath();
      final java.lang.Object other$newPath = other.getNewPath();
      if (this$newPath == null ? other$newPath != null : !this$newPath.equals(other$newPath)) return false;
      return true;
    }
    
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    protected boolean canEqual(final java.lang.Object other) {
      return other instanceof Util.NestedLocator;
    }
    
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @javax.annotation.Generated("lombok")
    public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      final java.lang.Object $mTail = this.getMTail();
      result = result * PRIME + ($mTail == null ? 0 : $mTail.hashCode());
      final java.lang.Object $mPos = this.getMPos();
      result = result * PRIME + ($mPos == null ? 0 : $mPos.hashCode());
      final java.lang.Object $that = this.getThat();
      result = result * PRIME + ($that == null ? 0 : $that.hashCode());
      final java.lang.Object $newName = this.getNewName();
      result = result * PRIME + ($newName == null ? 0 : $newName.hashCode());
      final java.lang.Object $newPath = this.getNewPath();
      result = result * PRIME + ($newPath == null ? 0 : $newPath.hashCode());
      return result;
    }
  }
}